// @generated by protoc-gen-connect-query v0.3.0 with parameter "target=ts"
// @generated from file eliza.proto (package buf.connect.demo.eliza.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import { SayRequest, SayResponse, UserRequest, UserResponse } from "./eliza_pb.js";

export const typeName = "buf.connect.demo.eliza.v1.ElizaService";

/**
 * @generated from rpc buf.connect.demo.eliza.v1.ElizaService.Say
 */
export const say = createQueryService({
  service: {
    methods: {
      say: {
        name: "Say",
        kind: MethodKind.Unary,
        I: SayRequest,
        O: SayResponse,
      },
    },
    typeName: "buf.connect.demo.eliza.v1.ElizaService",
  },
}).say;

/**
 * @generated from rpc buf.connect.demo.eliza.v1.ElizaService.CreateUser
 */
export const createUser = createQueryService({
  service: {
    methods: {
      createUser: {
        name: "CreateUser",
        kind: MethodKind.Unary,
        I: UserRequest,
        O: UserResponse,
      },
    },
    typeName: "buf.connect.demo.eliza.v1.ElizaService",
  },
}).createUser;
