// @generated by protoc-gen-connect-query v0.3.0 with parameter "target=ts"
// @generated from file etude.proto (package etude.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import { CreateUserRequest, CreateUserResponse } from "./etude_pb.js";

export const typeName = "etude.v1.EtudeService";

/**
 * @generated from rpc etude.v1.EtudeService.CreateUser
 */
export const createUser = createQueryService({
  service: {
    methods: {
      createUser: {
        name: "CreateUser",
        kind: MethodKind.Unary,
        I: CreateUserRequest,
        O: CreateUserResponse,
      },
    },
    typeName: "etude.v1.EtudeService",
  },
}).createUser;
