// @generated by protoc-gen-connect-es v0.10.0 with parameter "target=ts,import_extension=.ts"
// @generated from file etude.proto (package etude.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserRequest, GetUserResponse } from "./etude_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service etude.v1.EtudeService
 */
export const EtudeService = {
  typeName: "etude.v1.EtudeService",
  methods: {
    /**
     * @generated from rpc etude.v1.EtudeService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

